#springdoc.api-docs.path=/api-docs
server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tradestoredb
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
cron:
  expression: "* */30 * * * *"

springdoc:
  api-docs:
    path: /api-docs